[package]
name = "solikv-resp"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["codec"] }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
